### PR TITLE
from dev

### PR DESCRIPTION
**Pull request by linuxcaffe**
lotsa changes, mostly harmless

### CODE REVIEW

**Comment by linuxcaffe** [comment]
I think that addresses your fine suggestions.. ?

**Comment by linuxcaffe** [comment]
except for maybe the typo in the timew-android_fork.md file s/may/many/

**Comment by linuxcaffe** [comment]
is this "good to go"? is it waiting on a single typo? are ya ever coming back Markus? ;-)

**Comment by netmackan** [comment]
Is this pull request (#70) intended to replacing #68?
It is only #70 (the latest) that should be merged, right?

**Comment by linuxcaffe** [comment]
Right

**Pull request merged**
